name: marp CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        run: mkdir -p staging && chmod 777 marp && chmod 777 staging
      - name: Build HTML
        run: docker run --rm -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli -I marp -o staging
      - name: Build PDFs
        run: docker run --rm -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli -I marp -o staging --pdf
      - uses: actions/upload-artifact@v1
        with:
          name: PDFs-and-HTML
          path: staging
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest-pdfs
          files: |
            staging/*
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: staging
          CLEAN: trueh
